version: '3.3'
services:
  db:
    container_name: db
    image: postgres:13.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=employee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  seft-203:
    container_name: seft-203
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie'
    ports:
    - 15672:15672
    - 5672:5672